name: check

on:
  pull_request:
    paths:
      - foo/bar

jobs:
  check:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - run: echo '${{ toJSON(github) }}'
