name: merge queue

on:
  merge_group:
  push:
    branches: [foo]

jobs:
  check:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - run: |
          echo '${{ toJSON(github) }}'
          exit 1
