name: update

on:
  pull_request:
    types:
      - closed

jobs:
  update:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v3
      - run: ./update_pr_branches.sh
